<?php

/**
 * @file
 * An Internet Archive Book Reader extension for Islandora Compound Objects.
 * Custom behavior for Barnard Digital Collections.
 * @blame Benjamin Rosner, @br2490
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function barnard_compound_bookreader_preprocess_islandora_internet_archive_bookreader(array &$variables) {
  dpm('code hit.');
  $object = $variables['object'];
  $pid = $object->id;
  $ns = islandora_get_namespace($pid);

  $thumbs = explode(', ', variable_get('bc_islandora_bookreader_initial_thumbs'));
  $one_ups = explode(', ', variable_get('bc_islandora_bookreader_initial_1up'));

  if (in_array($pid, $thumbs) || in_array($ns, $thumbs)) {
    drupal_add_js([
      'islandoraInternetArchiveBookReader' =>
        ['bookReaderInitialMode' => 3],
    ], 'setting');
  }
  elseif (in_array($pid, $one_ups) || in_array($ns, $one_ups)) {
    drupal_add_js([
      'islandoraInternetArchiveBookReader' =>
        ['bookReaderInitialMode' => 1],
    ], 'setting');
  }

  $barnard_islandora_path = drupal_get_path('module', 'bc_islandora');

  // This is the extended BookReader that is to be called BEFORE IIAB.
  drupal_add_js("$barnard_islandora_path/js/compound_book_reader.js",
    [
      'group' => JS_LIBRARY,
      'weight' => -5,
    ]
  );
  
  // This just replaces the default with ours: it hides additional items, and
  // is not required for functionality.
  drupal_add_js("$barnard_islandora_path/js/barnard_islandora_internet_archive_bookreader.js",
    [
      'group' => JS_LIBRARY,
      'weight' => -5,
    ]
  );
}
